# Generated by Django 5.0.1 on 2024-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Биография')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Фотография')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('is_published', models.CharField(choices=[('DRAFT', 'Черновик'), ('PUBLISHED', 'Опубликованно')], default='PUBLISHED', max_length=15, verbose_name='Статус')),
                ('data_of_bird', models.DateField(blank=True, null=True, verbose_name='День рождения')),
            ],
            options={
                'ordering': ['-create'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
    ]
