# Generated by Django 5.0.1 on 2024-01-25 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('men', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='men',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='men.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='men',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='men.tags', verbose_name='Таг'),
        ),
        migrations.AddIndex(
            model_name='men',
            index=models.Index(fields=['create'], name='men_men_create_808c42_idx'),
        ),
    ]
